import type { Metadata } from "next";
import { Inter, Josefin_Sans, Oldenburg, Open_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";

const inter = Inter({
  subsets: ["latin"],
  variable: '--font-inter'
});

const openSans= Open_Sans({
  subsets: ["latin"],
  variable: '--font-openSans'
})
const oldenburg= Oldenburg({
  subsets: ["latin"],
  variable: '--font-oldenburg',
  weight: "400"
})
const josefin= Josefin_Sans({
  subsets: ["latin"],
  variable: '--font-josefin'
})

export const metadata: Metadata = {
  title: "Skinluxe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${openSans.variable} ${oldenburg.variable} ${josefin.variable}`}>{children}</body>
      <Footer />
    </html>
  );
}
